version: "3.5"
services:
  ${repository}:
    image: hatlonely/${repository}:${version}
    hostname: ${repository}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - "/var/docker/cloud/log:/var/docker/cloud/log"
      - "/var/docker/cloud/data:/var/docker/cloud/data"
    # ports:
    #   - "6061:6061"
    networks:
      - ${repository}net
      - go-accountnet
networks:
  ${repository}net:
    name: ${repository}net
  go-accountnet:
    external: true
    name: go-accountnet
