version: "3.5"
services:
  go-cloud:
    image: hatlonely/go-cloud:${version}
    hostname: go-cloud
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - "/var/docker/cloud/log:/var/docker/cloud/log"
      - "/var/docker/cloud/data:/var/docker/cloud/data"
    # ports:
    #   - "6061:6061"
    networks:
      - go-cloudnet
      - go-accountnet
networks:
  go-cloudnet:
    name: go-cloudnet
  go-accountnet:
    external: true
    name: go-accountnet
